# Generated by Django 3.0.2 on 2020-01-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_ascii', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('iso2', models.CharField(max_length=2, null=True)),
                ('iso3', models.CharField(max_length=3, null=True)),
                ('admin_name', models.CharField(max_length=50, null=True)),
                ('capital', models.CharField(max_length=50, null=True)),
                ('population', models.IntegerField(max_length=50, null=True)),
            ],
        ),
    ]
