# Generated by Django 3.0.2 on 2020-01-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='continent',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
