# Generated by Django 3.0.2 on 2020-01-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='town',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='town',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='town',
            name='name_ascii',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='town',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
