# Generated by Django 3.0.2 on 2020-01-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_town_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.CharField(default='https://bit.ly/37UONby', max_length=500),
        ),
    ]
