# Generated by Django 3.0.2 on 2020-01-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20200109_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='lat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='town',
            name='lng',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='town',
            name='population',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
