# Generated by Django 3.0.2 on 2020-01-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20200109_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='users',
            new_name='visitors',
        ),
    ]
