# Generated by Django 3.0.2 on 2020-01-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20200109_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='admin_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='capital',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='iso2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='iso3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='lat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='town',
            name='lng',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='town',
            name='population',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
