# Generated by Django 3.0.2 on 2020-01-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20200109_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
