# Generated by Django 3.0.2 on 2020-01-09 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0007_auto_20200109_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
