# Generated by Django 3.0.2 on 2020-01-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_auto_20200109_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='podium_1_User',
            new_name='podium_1_user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='podium_2_User',
            new_name='podium_2_user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='podium_3_User',
            new_name='podium_3_user',
        ),
    ]
