# Generated by Django 3.0.2 on 2020-01-09 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0009_auto_20200109_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='requested',
            field=models.ManyToManyField(blank=True, related_name='groups_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
