# Generated by Django 3.0.2 on 2020-01-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_group_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='requested',
            new_name='requests',
        ),
    ]
