# Generated by Django 3.0.2 on 2020-01-09 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0011_auto_20200109_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='towns', to=settings.AUTH_USER_MODEL),
        ),
    ]
