# Generated by Django 3.0.2 on 2020-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='https://bit.ly/37UONby', max_length=500),
        ),
    ]
