# Generated by Django 3.0.2 on 2020-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dexterity',
            field=models.CharField(choices=[('LH', 'Left-Handed'), ('RH', 'Right-Handed')], default='RH', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
